config/routes.rb
Rails.application.routes.draw do
  root 'coins#index'
  get 'about', to: 'pages#about'
  resources :coins, only: [:index, :show]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/coin.rb
class Coin < ApplicationRecord
end

app/models/transaction.rb
class Transaction < ApplicationRecord
  belongs_to :coin
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern

  def index
    if params[:search]
      @coins = Coin.where("name LIKE ?", "%#{params[:search]}%")
    else
      @coins = Coin.all
    end
  end
end

app/controllers/coins_controller.rb
class CoinsController < ApplicationController
  def index
    if params[:search]
      @coins = Coin.where("name LIKE ?", "%#{params[:search]}%").page(params[:page])
    else
      @coins = Coin.page(params[:page])
    end
  end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def about
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/coins_helper.rb
module CoinsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/coins/index.html.erb
<h1>Coins</h1>
<ul>
  <% @coins.each do |coin| %>
    <li><%= link_to coin.name, coin_path(coin) %></li>
  <% end %>
</ul>

<!-- Search Form -->

<%= form_with url: coins_path, method: :get, class: "mb-4" do |form| %>
  <div class="input-group">
    <%= form.text_field :search, placeholder: "Search coins by name", class: "form-control" %>
    <div class="input-group-append">
      <%= form.submit "Search", class: "btn btn-primary" %>
    </div>
  </div>
<% end %>

<!-- Pagination -->

<%= paginate @coins %>

<!-- ERB conditional -->

<% if @coin.price > 1000 %>
  <p>This coin is expensive!</p>
<% else %>
  <p>This coin is affordable.</p>
<% end %>

app/views/coins/show.html.erb
<h1><%= @coin.name %></h1>
<p>Symbol: <%= @coin.symbol %></p>
<p>Price: <%= @coin.price %></p>
<p>Market Cap: <%= @coin.market_cap %></p>
<p>24h Volume: <%= @coin.volume_24h %></p>
<p>24h Change: <%= @coin.change_24h %></p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Crypto Tracker</title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" rel="stylesheet">
</head>
<body>
  <nav class="navbar navbar-expand-lg navbar-light bg-light">
    <a class="navbar-brand" href="/">Crypto Tracker</a>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav">
        <li class="nav-item">
          <%= link_to 'Home', root_path, class: 'nav-link' %>
        </li>
        <li class="nav-item">
          <%= link_to 'About', about_path, class: 'nav-link' %>
        </li>
      </ul>
    </div>
  </nav>
  <div class="container">
    <%= yield %>
  </div>
</body>
</html>

app/views/pages/about.html.erb
<h1>About</h1>
<p>This application uses data from the Coinranking API and CoinMarketCap API.</p>